# Start with a base image that has Java installed
FROM openjdk:17-jdk-slim

# # Set the working directory in the container
WORKDIR /app

# # Copy the Spring Boot application's JAR file into the container
# # Replace "app.jar" with your JAR file name, e.g., "your-application-0.0.1-SNAPSHOT.jar"
COPY target/amateuraces-0.0.1-SNAPSHOT.jar /app/amateuraces-0.0.1-SNAPSHOT.jar

# COPY . .

# # Expose the port that the application runs on
EXPOSE 3306

# # Define the command to run the application
ENTRYPOINT ["java", "-jar", "/app/amateuraces-0.0.1-SNAPSHOT.jar"]

# COPY . ./
# # Ensure mvnw has LF line endings
# RUN sed -i 's/\r$//' mvnw && \
#     chmod +x mvnw && \
#     ./mvnw clean install -DskipTests
# EXPOSE 3306
# ENTRYPOINT ["java","-jar","target/amateuraces-0.0.1-SNAPSHOT.jar"]