version: '3.8'
services:
  db:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: goodpassword
      MYSQL_DATABASE: amateuraces
      MYSQL_USER: admin
      MYSQL_PASSWORD: goodpassword
    ports:
      - "3306:3306"

  app:
    build: .
    container_name: springboot-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/amateuraces
      SPRING_DATASOURCE_USERNAME: your_user
      SPRING_DATASOURCE_PASSWORD: your_password
    ports:
      - "8080:8080"
    depends_on:
      - db