
GET http://localhost:8080/matches

###

POST http://localhost:8080/players
Content-Type: application/json

{
    "id" : 1, 
    "name" : "player"
     
}
###
GET http://localhost:8080/players/

###

DELETE http://localhost:8080/books/3

###
GET http://localhost:8080/books/3

###
POST http://localhost:8080/players/
Content-Type: application/json

{
    "title": "I, Robot"
}

###
PUT http://localhost:8080/books/3
Content-Type: application/json

{
    "title": "Sapiens"
}

###
GET http://localhost:8080/players/
