### POST ADMIN INFO TO USER AFTER CREATION OF USER WITH AUTHORITY
POST http://localhost:8080/users/1/admins
Content-Type: application/json
Authorization: Basic admin goodpassword

{
    "name":"Admin",
    "phoneNumber" : "88888888"
}

### POST NEW USER IF NOT AUTHORIZED AUTHORIIES FIXED ROLE_USER
# By right users would only key in username, email and password but in the event they try to change authority it will fail
POST http://localhost:8080/users
Content-Type: application/json

{
    "username": "betatester",
    "email": "betatester@email.com",
    "password": "betatester"   
}

### POST NEW USER IF NOT AUTHORIZED AUTHORIIES FIXED ROLE_USER
POST http://localhost:8080/users
Content-Type: application/json

{
    "username": "user1",
    "email": "user1@email.com",
    "password": "betatester"   
}
### POST NEW USER
POST http://localhost:8080/users
Content-Type: application/json


{
    "username": "user2",
    "email": "user2@email.com",
    "password": "betatester"   
}

### POST NEW USER
POST http://localhost:8080/users
Content-Type: application/json

{
    "username": "user3",
    "email": "user3@email.com",
    "password": "betatester"   
}

### POST NEW USER
POST http://localhost:8080/users
Content-Type: application/json

{
    "username": "user4",
    "email": "user4@email.com",
    "password": "betatester"   
}

###
POST http://localhost:8080/users
Content-Type: application/json


{
    "username": "user5",
    "email": "user5@email.com",
    "password": "betatester"   
}

###
POST http://localhost:8080/users
Content-Type: application/json


{
    "username": "user6",
    "email": "user6@email.com",
    "password": "betatester"   
}

###
POST http://localhost:8080/users
Content-Type: application/json


{
    "username": "user7",
    "email": "user7@email.com",
    "password": "betatester"   
}

### POST PLAYER INFO TO USER AFTER CREATION OF USER
POST http://localhost:8080/users/2/players
Content-Type: application/json
Authorization: Basic betatester betatester

{
    "name":"Jenny",
    "phoneNumber" :"86783921",
    "email" : "jenny@gmail.com",
    "age" : 18,
    "gender" : "Female",
    "elo": 1500
}

### POST PLAYER INFO TO USER AFTER CREATION OF USER
# Show that player can create 
POST http://localhost:8080/users/3/players
Content-Type: application/json
Authorization: Basic user1 betatester

{
    "name":"Alpha",
    "phoneNumber" :"12345678",
    "email" : "alpha@gmail.com",
    "age" : 18,
    "gender" : "Female",
    "elo": 1510
}

### POST PLAYER INFO TO USER AFTER CREATION OF USER
# Show that player can create 
POST http://localhost:8080/users/4/players
Content-Type: application/json
Authorization: Basic user2 betatester

{
    "name":"Lolly",
    "phoneNumber" :"67389201",
    "email" : "lolly@gmail.com",
    "age" : 21,
    "gender" : "Female",
    "elo": 1520
}

### POST PLAYER INFO TO USER AFTER CREATION OF USER
# Show that player can create 
POST http://localhost:8080/users/5/players
Content-Type: application/json
Authorization: Basic user3 betatester

{
    "name":"Molly",
    "phoneNumber" :"84637823",
    "email" : "molly@gmail.com",
    "age" : 25,
    "gender" : "Female",
    "elo": 1530
}

### POST PLAYER INFO TO USER AFTER CREATION OF USER
# Show that player can create 
POST http://localhost:8080/users/6/players
Content-Type: application/json
Authorization: Basic user4 betatester

{
    "name":"Phan",
    "phoneNumber" :"88888821",
    "email" : "phan@gmail.com",
    "age" : 16,
    "gender" : "Female",
    "elo": 1540
}

### POST PLAYER INFO TO USER AFTER CREATION OF USER
# Show that player can create 
POST http://localhost:8080/users/7/players
Content-Type: application/json
Authorization: Basic user5 betatester

{
    "name":"Gina",
    "phoneNumber" :"35628910",
    "email" : "gina@gmail.com",
    "age" : 18,
    "gender" : "Female",
    "elo": 1550
}

### POST PLAYER INFO TO USER AFTER CREATION OF USER
# Show that player can create 
POST http://localhost:8080/users/8/players
Content-Type: application/json
Authorization: Basic user6 betatester

{
    "name":"Lindy",
    "phoneNumber" :"88288821",
    "email" : "lindy@gmail.com",
    "age" : 21,
    "gender" : "Female",
    "elo": 1560
}

###
# Show that player can create 
POST http://localhost:8080/users/9/players
Content-Type: application/json
Authorization: Basic user7 betatester

{
    "name":"Fairy",
    "phoneNumber" :"88266721",
    "email" : "fairy@gmail.com",
    "age" : 30,
    "gender" : "Female",
    "elo": 1570
}

### Showcase user cannot post in admin
POST http://localhost:8080/users/1/admins
Content-Type: application/json
Authorization: Basic betatester betatester

{
    "name":"Alphabravo",
    "phoneNumber" : "88888888"
}

### Tournament
POST http://localhost:8080/tournaments
Content-Type: application/json
Authorization: Basic admin goodpassword


{
    "name": "test1",
    "gender": "Female",
    "elorequirement": 100,
    "maxPlayers":8,
    "location": "Singapore",
    "description":"newbie training session",
    "startDate": "2024-12-29",
    "endDate":"2024-12-31"
}

### Tournament
GET http://localhost:8080/tournaments/1
Content-Type: application/json
Authorization: Basic admin goodpassword

### Get Matches
GET http://localhost:8080/tournaments/1/matches
Content-Type: application/json
Authorization: Basic admin goodpassword

### POST Player to tournament
POST http://localhost:8080/tournaments/1/players
Authorization: Basic betatester betatester 

### POST Player to tournament
POST http://localhost:8080/tournaments/1/players
Authorization: Basic user1 betatester 

### PLAYER TO WITHDRAW FROM TOURNAMENT
DELETE http://localhost:8080/tournaments/1/players/2
Authorization: Basic betatester betatester

### POST Player to tournament
POST http://localhost:8080/tournaments/1/players
Authorization: Basic user2 betatester 

### POST Player to tournament
POST http://localhost:8080/tournaments/1/players
Authorization: Basic user3 betatester

### POST Player to tournament
POST http://localhost:8080/tournaments/1/players
Authorization: Basic user4 betatester

### POST Player to tournament
POST http://localhost:8080/tournaments/1/players
Authorization: Basic user5 betatester

### POST Player to tournament
POST http://localhost:8080/tournaments/1/players
Authorization: Basic user6 betatester

### POST Player to tournament
POST http://localhost:8080/tournaments/1/players
Authorization: Basic user7 betatester

### POST Player to tournament FAILS BECAUSE THIS IS ADMIN
POST http://localhost:8080/tournaments/1/players
Authorization: Basic admin goodpassword 


### Initialise Draw
POST http://localhost:8080/tournaments/1/generate
Content-Type: application/json
Authorization: Basic admin goodpassword

### MATCH 1 RESULTS
PUT http://localhost:8080/tournaments/1/matches/1
Content-Type: application/json
Authorization: Basic admin goodpassword

{
  "score": "2-3",
  "completed": true
}

### MATCH 2 RESULTS
PUT http://localhost:8080/tournaments/1/matches/2
Content-Type: application/json
Authorization: Basic admin goodpassword

{
  "score": "2-3",
  "completed": true
}

### MATCH 3 RESULTS
PUT http://localhost:8080/tournaments/1/matches/3
Content-Type: application/json
Authorization: Basic admin goodpassword

{
  "score": "2-3",
  "completed": true
}

### MATCH 4 RESULTS
PUT http://localhost:8080/tournaments/1/matches/4
Content-Type: application/json
Authorization: Basic admin goodpassword

{
  "score": "2-3",
  "completed": true
}

### MATCH 5 RESULTS
PUT http://localhost:8080/tournaments/1/matches/5
Content-Type: application/json
Authorization: Basic admin goodpassword

{
  "score": "2-3",
  "completed": true
}

### MATCH 6 RESULTS
PUT http://localhost:8080/tournaments/1/matches/6
Content-Type: application/json
Authorization: Basic admin goodpassword

{
  "score": "2-3",
  "completed": true
}

### MATCH 7 RESULTS
PUT http://localhost:8080/tournaments/1/matches/7
Content-Type: application/json
Authorization: Basic admin goodpassword

{
  "score": "2-3",
  "completed": true
}

### Tournament
GET http://localhost:8080/tournaments

### GET MATCHES
GET http://localhost:8080/matches
Authorization: Basic admin goodpassword

### GET PLAYERS IN TOURNAMENT ID 1 
GET http://localhost:8080/tournaments/1/players

### GET SPECIFIC PLAYER 
GET http://localhost:8080/users/3/players

### DELETE USER 

DELETE http://localhost:8080/users/3
Authorization: Basic admin goodpassword



### UPDATE USER ONLY ALLOWED TO CHANGE PASSWORD
PUT http://localhost:8080/users/2
Content-Type: application/json
Authorization: Basic betatester betatester


{
    "username" : "betatester123",
    "email" : "use@email.com",
    "password": "betatester123"
    
}

### POST NEW USER SHOWCASE THAT MUST BE AUTHORIZED TO CREATE ADMIN

POST http://localhost:8080/users
Content-Type: application/json
Authorization: Basic betatester betatester

{
    "username": "showcase",
    "email" : "test@email.com",
    "password": "betatester",
    "authorities":"ROLE_ADMIN"
}

### UPDATE PLAYER DETAILS
PUT http://localhost:8080/users/2/players/2
Content-Type: application/json
Authorization: Basic admin goodpassword

{
    "name":"Johnny",
    "phoneNumber" : "12345678",
    "elo": "1000",
    "age" : 20,
    "gender" : "Male"
}

### 

DELETE http://localhost:8080/tournaments/1
Authorization: Basic admin goodpassword

### Tournament
GET http://localhost:8080/tournaments

###

DELETE http://localhost:8080/tournaments/1/matches/3
Authorization: Basic admin goodpassword

### GET USERS
GET http://localhost:8080/users

### GET Players
GET http://localhost:8080/players

### GET ADMIN
GET http://localhost:8080/admin
Authorization: Basic admin goodpassword