### POST NEW USER IF NOT AUTHORIZED AUTHORIIES FIXED ROLE_USER
# By right users would only key in username and password but in the event they try to change authority it will fail
POST http://localhost:8080/users
Content-Type: application/json


{
    "username": "betatester",
    "email": "betatester@email.com",
    "password": "betatester"   
}


### POST NEW USER IF NOT AUTHORIZED AUTHORIIES FIXED ROLE_USER
# By right users would only key in username and password but in the event they try to change authority it will fail
POST http://localhost:8080/users
Content-Type: application/json


{
    "username": "username",
    "email": "user@email.com",
    "password": "betatester"   
}
###
POST http://localhost:8080/users
Content-Type: application/json


{
    "username": "usernames",
    "email": "use@email.com",
    "password": "betatester"   
}

###
POST http://localhost:8080/users
Content-Type: application/json


{
    "username": "usernamess",
    "email": "ue@email.com",
    "password": "betatester"   
}

###
POST http://localhost:8080/users
Content-Type: application/json


{
    "username": "usernamesss",
    "email": "u@email.com",
    "password": "betatester"   
}

###
POST http://localhost:8080/users
Content-Type: application/json


{
    "username": "usernamessss",
    "email": "ude@email.com",
    "password": "betatester"   
}

###
POST http://localhost:8080/users
Content-Type: application/json


{
    "username": "usernamesssss",
    "email": "de@email.com",
    "password": "betatester"   
}

###
POST http://localhost:8080/users
Content-Type: application/json


{
    "username": "usernamessssss",
    "email": "e@email.com",
    "password": "betatester"   
}

### POST PLAYER INFO TO USER AFTER CREATION OF USER
# Show that cannot create player for admin
POST http://localhost:8080/users/1/players
Content-Type: application/json
Authorization: Basic admin goodpassword

{
    "name":"Alphabravo",
    "phoneNumber" :"88888888",
    "email" : "alphabravo@gmail.com",
    "age" : 18,
    "gender" : "Female"
}

### POST PLAYER INFO TO USER AFTER CREATION OF USER
# Show that player can create 
POST http://localhost:8080/users/2/players
Content-Type: application/json
Authorization: Basic username betatester

{
    "name":"Alpha",
    "phoneNumber" :"12345678",
    "email" : "alphabo@gmail.com",
    "age" : 18,
    "gender" : "Female"
}

### POST PLAYER INFO TO USER AFTER CREATION OF USER
# Show that player can create 
POST http://localhost:8080/users/3/players
Content-Type: application/json
Authorization: Basic betatester betatester

{
    "name":"Alphabravos",
    "phoneNumber" :"88888882",
    "email" : "alphabravo@gmail.com",
    "age" : 18,
    "gender" : "Female"
}

### POST PLAYER INFO TO USER AFTER CREATION OF USER
# Show that player can create 
POST http://localhost:8080/users/4/players
Content-Type: application/json
Authorization: Basic usernames betatester

{
    "name":"Alphabravo",
    "phoneNumber" :"88888888",
    "email" : "alphabravo@gmail.com",
    "age" : 18,
    "gender" : "Female"
}

### POST PLAYER INFO TO USER AFTER CREATION OF USER
# Show that player can create 
POST http://localhost:8080/users/5/players
Content-Type: application/json
Authorization: Basic usernames betatester

{
    "name":"pha",
    "phoneNumber" :"88888821",
    "email" : "alpo@gmail.com",
    "age" : 18,
    "gender" : "Female"
}

### POST PLAYER INFO TO USER AFTER CREATION OF USER
# Show that player can create 
POST http://localhost:8080/users/6/players
Content-Type: application/json
Authorization: Basic usernames betatester

{
    "name":"phad",
    "phoneNumber" :"88882821",
    "email" : "alpo@gmail.com",
    "age" : 18,
    "gender" : "Female"
}

### POST PLAYER INFO TO USER AFTER CREATION OF USER
# Show that player can create 
POST http://localhost:8080/users/7/players
Content-Type: application/json
Authorization: Basic usernames betatester

{
    "name":"phass",
    "phoneNumber" :"88288821",
    "email" : "alpo@gmail.com",
    "age" : 18,
    "gender" : "Female"
}

###
# Show that player can create 
POST http://localhost:8080/users/8/players
Content-Type: application/json
Authorization: Basic usernames betatester

{
    "name":"phasssasds",
    "phoneNumber" :"88266721",
    "email" : "poasdpoad@gmail.com",
    "age" : 18,
    "gender" : "Female"
}
###
# Show that player can create 
POST http://localhost:8080/users/9/players
Content-Type: application/json
Authorization: Basic usernames betatester

{
    "name":"phaswerirhtews",
    "phoneNumber" :"882883451",
    "email" : "alpo13498@gmail.com",
    "age" : 18,
    "gender" : "Female"
}

### Showcase user cannot post in admin
POST http://localhost:8080/users/1/admins
Content-Type: application/json
Authorization: Basic betatester betatester

{
    "name":"Alphabravo",
    "phoneNumber" : "88888888"
}

### POST ADMIN INFO TO USER AFTER CREATION OF USER
POST http://localhost:8080/users/1/admins
Content-Type: application/json
Authorization: Basic admin goodpassword

{
    "name":"Alphabravo",
    "phoneNumber" : "88888888"
}

### GET USERS

GET http://localhost:8080/users

### GET Players
GET http://localhost:8080/players

### GET ADMIN
GET http://localhost:8080/admin
Authorization: Basic admin goodpassword

### Tournament
POST http://localhost:8080/tournaments
Content-Type: application/json
Authorization: Basic admin goodpassword


{
    "name": "test1",
    "gender": "Female",
    "elorequirement": 100,
    "maxPlayers":8,
    "location": "Singapore",
    "description":"newbie training session",
    "startDate": "2024-12-29",
    "endDate":"2024-12-31"
}

### Tournament
GET http://localhost:8080/tournaments
Content-Type: application/json
Authorization: Basic admin goodpassword

### POST Player to tournament
POST http://localhost:8080/tournaments/1/players
Authorization: Basic username betatester 

### POST Player to tournament
POST http://localhost:8080/tournaments/1/players
Authorization: Basic betatester betatester 

### POST Player to tournament
POST http://localhost:8080/tournaments/1/players
Authorization: Basic usernames betatester 

### POST Player to tournament
POST http://localhost:8080/tournaments/1/players
Authorization: Basic usernamess betatester

### POST Player to tournament
POST http://localhost:8080/tournaments/1/players
Authorization: Basic usernamesss betatester

### POST Player to tournament
POST http://localhost:8080/tournaments/1/players
Authorization: Basic usernamessss betatester

### POST Player to tournament
POST http://localhost:8080/tournaments/1/players
Authorization: Basic usernamesssss betatester

### POST Player to tournament
POST http://localhost:8080/tournaments/1/players
Authorization: Basic usernamessssss betatester

### POST Player to tournament
POST http://localhost:8080/tournaments/1/players
Authorization: Basic admin goodpassword 

### POST DRAW ALGO

POST http://localhost:8080/tournaments/1/matches
Content-Type: application/json
Authorization: Basic admin goodpassword

{

}

### Initialise Draw
POST http://localhost:8080/tournaments/1/initialise-draw
Content-Type: application/json


### Print Draw
POST http://localhost:8080/tournaments/1/update-next-round
Content-Type: application/json

###
POST http://localhost:8080/tournaments/1/matches/1/result
Content-Type: application/json
Authorization: Basic admin goodpassword

{
    "winnerId": 2,
    "loserId": 3,
    "score": "15-40"
}
### GET MATCHES

GET http://localhost:8080/matches
Authorization: Basic admin goodpassword
###
GET http://localhost:8080/tournaments/1/players

###
DELETE http://localhost:8080/tournaments/1/players/2
Authorization: Basic betatester betatester

### Tournament
GET http://localhost:8080/tournaments

### GET SPECIFIC PLAYER 
GET http://localhost:8080/users/2/players

### DELETE USER 

DELETE http://localhost:8080/users/3
Authorization: Basic admin goodpassword



### UPDATE USER ONLY ALLOWED TO CHANGE PASSWORD
PUT http://localhost:8080/users/3
Content-Type: application/json
Authorization: Basic admin goodpassword


{
    "username" : "betatester",
    "password": "passwordtest"
    
}

### POST NEW USER SHOWCASE THAT MUST BE AUTHORIZED TO CREATE ADMIN

POST http://localhost:8080/users
Content-Type: application/json
Authorization: Basic betatester betatester


{
    "username": "betatester",
    "password": "betatester",
    "authorities":"ROLE_ADMIN"
}

### UPDATE PLAYER DETAILS
PUT http://localhost:8080/users/1/players/1
Content-Type: application/json
Authorization: Basic admin goodpassword

{
    "name":"Admin",
    "phoneNumber" : "123456789",
    "email" : "johnny@gmail.com",
    "age" : 200,
    "gender" : "Male"
}

### POST PLAYER INFO TO USER AFTER CREATION OF USER
POST http://localhost:8080/users/3/players
Content-Type: application/json
Authorization: Basic username password

{
    "name":"Alphabravo",
    "phoneNumber" :88888888,
    "email" : "alphabravo@gmail.com",
    "age" : 18,
    "gender" : "Female"
}




###
PUT http://localhost:8080/tournaments/1
Content-Type: application/json
Authorization: Basic admin goodpassword


{
    "name": "jon",
    "elorequirement": 9999
}
### 

DELETE http://localhost:8080/tournaments/1
Authorization: Basic admin goodpassword

###
POST http://localhost:8080/players
Content-Type: application/json
Authorization: Basic admin goodpassword

{
    "name": "I, Robot"
}

###
PUT http://localhost:8080/players/3
Content-Type: application/json
Authorization: Basic admin goodpassword


{
    "name": "balloon"
    
}

###
PUT http://localhost:8080/highlights/2
Content-Type: application/json
Authorization: Basic betatester betatester


{
    "tournamentOfTheMonth": "jon"
}

### Highlights
GET http://localhost:8080/highlights

###

POST http://localhost:8080/highlights
Content-Type: application/json
Authorization: Basic admin goodpassword

{
    "tournamentOfTheMonth" : "testing"
     
}

###

DELETE http://localhost:8080/highlights/4
Authorization: Basic admin goodpassword

### Tournament
GET http://localhost:8080/tournaments

###

POST http://localhost:8080/tournaments
Content-Type: application/json
Authorization: Basic admin goodpassword

{
    "name" : "US OPEN",
    "elorequirement" : 1500
     
}

###
PUT http://localhost:8080/tournaments/2
Content-Type: application/json
Authorization: Basic admin goodpassword


{
    "name": "united states of america"
}

###

DELETE http://localhost:8080/tournaments/1
Authorization: Basic admin goodpassword

### Match
GET http://localhost:8080/matches

###

POST http://localhost:8080/matches
Content-Type: application/json
Authorization: Basic admin goodpassword

{
    "Tournament"
    "Player1"
}

###

DELETE http://localhost:8080/matches/3
Authorization: Basic admin goodpassword